### ISSUE TITLE
Recent Updates

### ISSUE THREAD

**Issue by HumanTree92** [ESX-Org/esx_weashops#19]
After the recent updates when i go to the Legal Weapon Shop there is only 1 gun in there the Pistol. But When i go to the the Illegal Weapon Shop there is no guns in there. I haven't changed anything in my DB. All my scripts all default scripts. All my scripts have been updated. But still not working correctly. Now before i updated it today i was getting this error

Error running call reference function for resource esx_weashops: citizen:/scripting/lua/scheduler.lua:348: server/main.lua:65: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:65: in upvalue 'cb'
        server/main.lua:33: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:334: in function <citizen:/scripting/lua/scheduler.lua:333>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:333: in function <citizen:/scripting/lua/scheduler.lua:332>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:348: in function <citizen:/scripting/lua/scheduler.lua:319>
[ERROR] [MySQL] Check the error above, an error happens when executing the callback from the query : "SELECT * FROM weashops {=}"

But after updating it today i don't get this error but still the problem of weapons not showing up is still there. Now this was working on Apr 24, 2018 but with the recent updates it has broke my weapon shops.

**Comment by ElPumpo** [comment]
My bad for merging an awful PR...

**Comment by HumanTree92** [comment]
Its ok. Thanks for reverting it back.
