### ISSUE TITLE
Items in gun shop are in FR, instead of EN even set in config.lua

### ISSUE THREAD

**Issue by SGTGunner** [ESX-Org/esx_weashops#26]
Items that appear in FR, even though the config.lua is set to `en`.
The menu for license and shop are in English though.

![fivem_2018-08-18_15-18-12](https://user-images.githubusercontent.com/13827892/44303622-333d9e00-a2fa-11e8-9a5f-663b20ce81d9.jpg)

Example shown above.

**Comment by ElPumpo** [comment]
Use the proper locale for ESX
