### ISSUE TITLE
Error while executing sql

### ISSUE THREAD

**Issue by CMDTelhada** [ESX-Org/esx_weashops#28]
When adding sql I get this error
and it does not create the items, plus the tables are created normally
http://prntscr.com/l9gouv

**Comment by xnubil** [comment]
put a comma in the heading right after `zone` ,
`INSERT INTO `weashops` (`zone`, `item`, `price`) VALUES`

**Comment by Bluethefurry** [comment]
this was fixed with https://github.com/ESX-Org/esx_weashops/pull/31

**Comment by ElPumpo** [comment]
542ff5a50566cd94510994811e72bae262543fdc
