### ISSUE TITLE
attempt to call a nil value (field 'hasWeapon')

### ISSUE THREAD

**Issue by JEStudios** [ESX-Org/esx_weashops#41]
Error running system event handling function for resource esx_weashops: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:65: attempt to call a nil value (field 'hasWeapon')
stack traceback:
        server/main.lua:65: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>

I get the above error when I try to buy a weapon from the shop using the latest weashop

**Comment by ElPumpo** [comment]
update esx
